const MK='run-league-market';let mkt=JSON.parse(localStorage.getItem(MK)||'null');if(!mkt||mkt.v!==2)mkt={v:2,cash:100,efforts:[],positions:[],resolved:[],pools:{},hist:{},settled:{},banks:{},week:null};const saveM=()=>localStorage.setItem(MK,JSON.stringify(mkt));
const FRIENDS=['Amy','John','David','Olivia','Maya','Theo','Priya','Sam','Jordan'];FRIENDS.forEach(f=>{if(mkt.banks[f]==null)mkt.banks[f]=100});
const hash=s=>{let h=9;for(const ch of s)h=Math.imul(h^ch.charCodeAt(0),387420489);return(h>>>0)/4294967295};
const weekStart=()=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d};
const weekKey=()=>weekStart().toISOString().slice(0,10);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const paceStr=p=>Math.floor(p)+':'+String(Math.round(p%1*60)).padStart(2,'0');
const toast=t=>{const n=document.createElement('div');n.className='toast';n.textContent=t;document.body.append(n);setTimeout(()=>n.remove(),2600)};
let courseList=[],courseById={};fetch('../data/courses.json').then(r=>r.json()).then(x=>{courseList=x;x.forEach(c=>courseById[c.id]=c);renderMarket()});
window.__logEffort=e=>{mkt.efforts.push({...e,date:new Date().toISOString()});saveM();renderMarket()};
const CHALLENGE_POOL=[['Extreme Hike','Scottish Highlands'],['Ridge Ultra','Lake District'],['Night Trail','Epping Forest'],['Canal 10K','Camden'],['Coastal Half','Brighton'],['Fell Race','Peak District'],['Storm Run','Snowdonia'],['Bridge Loop','South Bank']];
function resume(name){if(name==='You'){const done=[...new Set(mkt.efforts.map(e=>e.courseId))].map(id=>courseById[id]).filter(Boolean);return done.map(c=>({lvl:c.difficulty,title:c.name,where:c.area})).sort((a,b)=>b.lvl-a.lvl).slice(0,3)}return Array.from({length:3},(_,i)=>{const r=n=>hash(name+'ch'+i+n),[title,where]=CHALLENGE_POOL[Math.floor(r(1)*CHALLENGE_POOL.length)];return{lvl:3+Math.floor(r(2)*7),title,where}}).sort((a,b)=>b.lvl-a.lvl)}
const climber=name=>Math.max(3,...resume(name).map(c=>c.lvl));
function stats(name){const wk=weekKey();if(name==='You'){const ws=weekStart(),ef=mkt.efforts.filter(e=>new Date(e.date)>=ws),km=ef.reduce((n,e)=>n+e.km,0),secs=ef.reduce((n,e)=>n+e.seconds,0);return{name,km,pace:km>0?secs/60/km:5.6,runs:ef.length}}const r=n=>hash(name+wk+n);return{name,km:18+r(1)*38,pace:4.5+r(2)*2,runs:2+Math.floor(r(3)*7)}}
function markets(){const wk=weekKey(),fs=FRIENDS.map(stats).sort((a,b)=>b.km-a.km),km1=[fs[0],fs[1]],km2=[fs[2],fs[3]],rest=fs.slice(4).sort((a,b)=>a.pace-b.pace),cr=[rest[0],rest[1]],me=stats('You'),rival=rest[2];
const course=courseList[Math.floor(hash('course'+wk)*courseList.length)];
const kmP=(a,b)=>clamp(a.km**2/(a.km**2+b.km**2),.12,.88);
const t=(s,c)=>s.pace*c.distanceKm*(1+c.incline*.015);
const crsP=(a,b,c)=>clamp(1/(1+Math.exp((t(a,c)-t(b,c))/(t(b,c)*.04)))+(climber(a.name)-climber(b.name))*.02*(c.incline/5),.1,.9);
return [
{id:'km1-'+wk,kind:'km',a:km1[0],b:km1[1],question:`Who will run more next week: ${km1[0].name} or ${km1[1].name}?`,modelP:kmP(km1[0],km1[1])},
{id:'crs-'+wk,kind:'course',a:cr[0],b:cr[1],course,question:`Who will complete ${course.name} quicker: ${cr[0].name} or ${cr[1].name}?`,modelP:crsP(cr[0],cr[1],course)},
{id:'km2-'+wk,kind:'km',a:km2[0],b:km2[1],question:`Who will run more next week: ${km2[0].name} or ${km2[1].name}?`,modelP:kmP(km2[0],km2[1])},
{id:'you-'+wk,kind:'km',a:me,b:rival,question:`Who will run more next week: You or ${rival.name}?`,modelP:clamp(kmP(me,rival),.08,.88)}]}
const sum=arr=>arr.reduce((n,x)=>n+x[1],0);
function implied(m){const p=mkt.pools[m.id],seed=12;const sa=sum(p.a)+seed*m.modelP,sb=sum(p.b)+seed*(1-m.modelP);return sa/(sa+sb)}
function pushP(m){const h=mkt.hist[m.id];h.push({t:Date.now(),p:implied(m)});if(h.length>240)mkt.hist[m.id]=h.slice(-240)}
function ensurePools(m){if(mkt.pools[m.id])return;const pool={a:[],b:[]};mkt.pools[m.id]=pool;mkt.hist[m.id]=[];const others=FRIENDS.filter(f=>f!==m.a.name&&f!==m.b.name),n=6+Math.floor(hash(m.id+'n')*5);const now=Date.now(),start=now-3*864e5;mkt.hist[m.id].push({t:start,p:m.modelP});
for(let i=0;i<n;i++){const r=k=>hash(m.id+'bf'+i+k),who=others[Math.floor(r(1)*others.length)],side=r(2)<implied(m)*.7+m.modelP*.3?'a':'b',amt=5+Math.floor(r(3)*4)*5;pool[side].push([who,amt]);mkt.hist[m.id].push({t:start+(now-start)*(i+1)/(n+1),p:implied(m)})}saveM()}
function graph(m){const h=mkt.hist[m.id],n=h.length,X=i=>(n<2?300:i/(n-1)*300).toFixed(1),Y=p=>(60-p*52-4).toFixed(1),line=h.map((pt,i)=>`${X(i)},${Y(pt.p)}`).join(' ');return `<svg class="odds-graph" viewBox="0 0 300 60" preserveAspectRatio="none"><line x1="0" y1="${Y(.5)}" x2="300" y2="${Y(.5)}" class="mid"/><polygon points="0,60 ${line} 300,60" class="area"/><polyline points="${line}" class="line"/><circle cx="300" cy="${Y(implied(m))}" r="3" class="dot"/></svg>`}
const myPos=m=>mkt.positions.filter(p=>p.id===m.id);
function projection(m,side,stake){const p=mkt.pools[m.id],win=sum(p[side])+stake,lose=sum(p[side==='a'?'b':'a']);return stake+stake/win*lose}
function bet(m,side,stake){if(m.a.name==='You'||m.b.name==='You')return toast("You can't bet on a market you're racing in");const person=side==='a'?m.a.name:m.b.name;if(mkt.cash<stake)return toast('Not enough balance');mkt.cash-=stake;mkt.pools[m.id][side].push(['You',stake]);mkt.positions.push({id:m.id,q:m.question,side,person,stake});pushP(m);saveM();toast(`£${stake} on ${person} — pot now £${(sum(mkt.pools[m.id].a)+sum(mkt.pools[m.id].b)).toFixed(0)}`);renderMarket()}
function settle(m){if(mkt.settled[m.id])return;let aWins;if(m.kind==='km'&&(m.a.name==='You'||m.b.name==='You'))aWins=m.a.km>=m.b.km;else aWins=hash(m.id+weekKey()+'res')<m.modelP;
const winner=aWins?m.a.name:m.b.name,pool=mkt.pools[m.id],winSide=aWins?pool.a:pool.b,loseSide=aWins?pool.b:pool.a,winSum=sum(winSide),loseSum=sum(loseSide);
const payFor=amt=>winSum>0?amt+amt/winSum*loseSum:amt;
winSide.forEach(([who,amt])=>{if(who!=='You')mkt.banks[who]+=payFor(amt)-amt});
loseSide.forEach(([who,amt])=>{if(who!=='You')mkt.banks[who]-=winSum>0?amt:0});
let collected=0;mkt.positions=mkt.positions.filter(pos=>{if(pos.id!==m.id)return true;const won=(pos.side==='a')===aWins,payout=won?payFor(pos.stake):(winSum>0?0:pos.stake);collected+=payout;mkt.cash+=payout;mkt.resolved.unshift({q:m.question,person:pos.person,won,pnl:payout-pos.stake,date:new Date().toISOString()});return false});
mkt.settled[m.id]={winner};mkt.hist[m.id].push({t:Date.now(),p:aWins?.97:.03});saveM();toast(`Settled — ${winner} wins the £${(winSum+loseSum).toFixed(0)} pot${collected?` · you collect £${collected.toFixed(2)}`:''}`);renderMarket()}
setInterval(()=>{if(!document.querySelector('#market-mode.active')||!courseList.length)return;const ms=markets();let moved=false;ms.forEach(m=>{if(mkt.settled[m.id])return;ensurePools(m);if(Math.random()<.25){const others=FRIENDS.filter(f=>f!==m.a.name&&f!==m.b.name),who=others[Math.floor(Math.random()*others.length)],side=Math.random()<implied(m)?'a':'b',amt=5+Math.floor(Math.random()*4)*5;mkt.pools[m.id][side].push([who,amt]);pushP(m);toast(`${who} put £${amt} on ${side==='a'?m.a.name:m.b.name}`);moved=true}});if(moved){saveM();renderMarket()}},9000);
const openProfiles=new Set();
function profileHTML(m,side){const s=side==='a'?m.a:m.b,pct=Math.round((side==='a'?implied(m):1-implied(m))*100),res=resume(s.name),lvl=climber(s.name);
return `<div class="player-profile"><div class="pp-stats"><span>${s.km.toFixed(0)} km/wk</span><span>${paceStr(s.pace)} /km</span><span>${s.runs} runs</span><span>climber LVL ${lvl}</span></div><b>CHALLENGE RÉSUMÉ</b>${res.length?res.map(c=>`<div class="pp-ch">LVL ${c.lvl} · ${c.title} — ${c.where}</div>`).join(''):'<div class="pp-ch muted">No logged challenges yet</div>'}<div class="pp-chance">${pct}% chance in this matchup${m.kind==='course'?` on ${m.course.name} (incline ${m.course.incline}/10, ${m.course.distanceKm} km)`:''}</div></div>`}
function renderMarket(){const list=document.querySelector('#market-list');if(!list||!courseList.length)return;
if(mkt.week!==weekKey()){mkt.positions.forEach(p=>mkt.cash+=p.stake);mkt.positions=[];mkt.pools={};mkt.hist={};mkt.settled={};mkt.week=weekKey();saveM()}
const ms=markets();ms.forEach(ensurePools);document.querySelector('#market-balance').textContent='£'+mkt.cash.toFixed(2);
list.innerHTML=ms.map(m=>{const p=implied(m),st=mkt.settled[m.id],hasYou=m.a.name==='You'||m.b.name==='You',pool=mkt.pools[m.id],pot=sum(pool.a)+sum(pool.b);
const statLine=m.kind==='km'?`${m.a.name}: ${m.a.km.toFixed(0)} km last wk · ${paceStr(m.a.pace)}/km — ${m.b.name}: ${m.b.km.toFixed(0)} km · ${paceStr(m.b.pace)}/km`:`${m.a.name}: ${paceStr(m.a.pace)}/km, climber LVL ${climber(m.a.name)} — ${m.b.name}: ${paceStr(m.b.pace)}/km, LVL ${climber(m.b.name)}`;
const row=(side,person,prob)=>{const key=m.id+':'+side,backers=pool[side].slice(-3).map(([w,a])=>`${w} £${a}`).join(' · ');
const btns=st?'':hasYou?(person==='You'?'<span class="self-note">can\'t back yourself</span>':'<span class="self-note">you\'re racing in this market</span>'):[5,10,25].map(v=>`<button class="bet-btn" data-id="${m.id}" data-side="${side}" data-stake="${v}" title="Returns £${projection(m,side,v).toFixed(2)} if right">£${v}</button>`).join('');
return `<div class="outcome-row${st&&st.winner===person?' won':''}"><button class="o-name-btn" data-key="${key}">${person} ▾</button><em>${Math.round(prob*100)}%</em><span class="o-odds">£${sum(pool[side]).toFixed(0)} in</span><div class="bet-btns">${btns}</div></div>${backers?`<div class="backers">${backers}</div>`:''}${openProfiles.has(key)?profileHTML(m,side):''}`};
const pos=myPos(m).map(x=>{const winSum=sum(pool[x.side])||x.stake,ret=x.stake+x.stake/winSum*sum(pool[x.side==='a'?'b':'a']);return `<div class="pos-note">You're in for £${x.stake} on ${x.person} — returns £${ret.toFixed(2)} if right (winners split the losers' pot)</div>`}).join('');
return `<article class="market-card${hasYou?' has-you':''}" data-id="${m.id}"><div class="market-q"><h3>${m.question}</h3>${st?`<span class="resolved-chip">RESOLVED · ${st.winner.toUpperCase()} WON</span>`:'<span class="countdown">CLOSES SUN 23:59</span>'}</div><p class="muted statline">${statLine}</p>${graph(m)}${row('a',m.a.name,p)}${row('b',m.b.name,1-p)}${pos}${st?'':`<button class="settle-btn" data-id="${m.id}">Fast-forward: settle market</button>`}<span class="vol">£${pot.toFixed(0)} POT</span></article>`}).join('');
list.querySelectorAll('.bet-btn').forEach(b=>b.onclick=()=>bet(ms.find(x=>x.id===b.dataset.id),b.dataset.side,Number(b.dataset.stake)));
list.querySelectorAll('.settle-btn').forEach(b=>b.onclick=()=>settle(ms.find(x=>x.id===b.dataset.id)));
list.querySelectorAll('.o-name-btn').forEach(b=>b.onclick=()=>{openProfiles.has(b.dataset.key)?openProfiles.delete(b.dataset.key):openProfiles.add(b.dataset.key);renderMarket()});
const el=document.querySelector('#market-side'),banks=[['You',mkt.cash],...FRIENDS.map(f=>[f,mkt.banks[f]])].sort((a,b)=>b[1]-a[1]);
el.innerHTML=`<div class="wallet-card"><span class="eyebrow">YOUR BALANCE</span><strong>£${mkt.cash.toFixed(2)}</strong><small>Started with £100 · play money</small><div class="wallet-demo"><button id="set-balance">Demo: set balance</button><span id="balance-edit" hidden><input id="balance-input" type="number" min="0" step="0.01" placeholder="£"><button id="balance-apply">Set</button></span></div></div><div class="side-block"><b>OPEN POSITIONS</b>${mkt.positions.length?mkt.positions.map(x=>`<div class="side-row"><span>${x.person}<small> £${x.stake} staked</small></span><strong>pot share</strong></div>`).join(''):'<p class="muted">No bets yet — back a friend.</p>'}</div><div class="side-block"><b>SETTLED</b>${mkt.resolved.length?mkt.resolved.slice(0,6).map(r=>`<div class="side-row"><span>${r.person}</span><strong class="${r.pnl>=0?'up':'down'}">${r.pnl>=0?'+':''}£${r.pnl.toFixed(2)}</strong></div>`).join(''):'<p class="muted">Nothing settled yet.</p>'}</div><div class="side-block"><b>TOP PREDICTORS</b>${banks.map((r,i)=>`<div class="side-row${r[0]==='You'?' mine':''}"><span>${['🥇','🥈','🥉'][i]||'·'} ${r[0]}</span><strong>£${r[1].toFixed(2)}</strong></div>`).join('')}</div>`;
el.querySelector('#set-balance').onclick=()=>{const ed=el.querySelector('#balance-edit'),inp=el.querySelector('#balance-input');ed.hidden=false;inp.value=mkt.cash.toFixed(2);inp.focus();inp.select()};
const applyBal=()=>{const v=Number(el.querySelector('#balance-input').value);if(!isFinite(v)||v<0)return toast('Enter a valid amount');mkt.cash=Math.round(v*100)/100;saveM();toast('Balance set to £'+mkt.cash.toFixed(2));renderMarket()};
el.querySelector('#balance-apply').onclick=applyBal;el.querySelector('#balance-input').onkeydown=e=>{if(e.key==='Enter')applyBal()}}
window.__renderMarket=renderMarket;
