const MK='run-league-market';let mkt=JSON.parse(localStorage.getItem(MK)||'null');
if(mkt&&mkt.v===2){const now=Date.now();Object.values(mkt.pools||{}).forEach(pool=>['a','b'].forEach(s=>{pool[s]=(pool[s]||[]).map((e,i)=>Array.isArray(e)?{who:e[0],amt:e[1],t:now-(2-i*.25)*864e5,p:null}:e)}));mkt.v=3}
if(!mkt||mkt.v!==3)mkt={v:3,cash:100,efforts:[],positions:[],resolved:[],pools:{},hist:{},settled:{},banks:{},week:null,earned:0,pledge:null};if(mkt.earned==null)mkt.earned=0;if(mkt.pledge===undefined)mkt.pledge=null;const saveM=()=>localStorage.setItem(MK,JSON.stringify(mkt));
const FRIENDS=['Amy','John','David','Olivia','Maya','Theo','Priya','Sam','Jordan'];FRIENDS.forEach(f=>{if(mkt.banks[f]==null)mkt.banks[f]=100});
const hash=s=>{let h=9;for(const ch of s)h=Math.imul(h^ch.charCodeAt(0),387420489);return(h>>>0)/4294967295};
const weekStart=()=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d};
const weekKey=()=>weekStart().toISOString().slice(0,10);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const paceStr=p=>Math.floor(p)+':'+String(Math.round(p%1*60)).padStart(2,'0');
const relTime=t=>{const s=(Date.now()-t)/1000;return s<3600?Math.max(1,Math.round(s/60))+'m ago':s<129600?Math.round(s/3600)+'h ago':Math.round(s/86400)+'d ago'};
const toast=t=>{const n=document.createElement('div');n.className='toast';n.textContent=t;document.body.append(n);setTimeout(()=>n.remove(),2600)};
let courseList=[],courseById={};fetch('../data/courses.json').then(r=>r.json()).then(x=>{courseList=x;x.forEach(c=>courseById[c.id]=c);renderMarket()});
window.__logEffort=e=>{mkt.efforts.push({...e,date:new Date().toISOString()});const streak=JSON.parse(localStorage.getItem('run-league-state')||'{"streak":0}').streak||0,mult=streak>=3?1.5:1,earn=Math.round(e.km*mult*100)/100;mkt.cash+=earn;mkt.earned=Math.round((mkt.earned+earn)*100)/100;saveM();toast(`+£${earn.toFixed(2)} sweat equity for ${e.km} km${mult>1?' (streak ×1.5)':''}`);renderMarket()};
const CHALLENGE_POOL=[['Extreme Hike','Scottish Highlands'],['Ridge Ultra','Lake District'],['Night Trail','Epping Forest'],['Canal 10K','Camden'],['Coastal Half','Brighton'],['Fell Race','Peak District'],['Storm Run','Snowdonia'],['Bridge Loop','South Bank']];
function resume(name){if(name==='You'){const done=[...new Set(mkt.efforts.map(e=>e.courseId))].map(id=>courseById[id]).filter(Boolean);return done.map(c=>({lvl:c.difficulty,title:c.name,where:c.area})).sort((a,b)=>b.lvl-a.lvl).slice(0,3)}return Array.from({length:3},(_,i)=>{const r=n=>hash(name+'ch'+i+n),[title,where]=CHALLENGE_POOL[Math.floor(r(1)*CHALLENGE_POOL.length)];return{lvl:3+Math.floor(r(2)*7),title,where}}).sort((a,b)=>b.lvl-a.lvl)}
const climber=name=>Math.max(3,...resume(name).map(c=>c.lvl));
function stats(name){const wk=weekKey();if(name==='You'){const ws=weekStart(),ef=mkt.efforts.filter(e=>new Date(e.date)>=ws),km=ef.reduce((n,e)=>n+e.km,0),secs=ef.reduce((n,e)=>n+e.seconds,0);return{name,km,pace:km>0?secs/60/km:5.6,runs:ef.length}}const r=n=>hash(name+wk+n);return{name,km:18+r(1)*38,pace:4.5+r(2)*2,runs:2+Math.floor(r(3)*7)}}
function markets(){const wk=weekKey(),fs=FRIENDS.map(stats).sort((a,b)=>b.km-a.km),km1=[fs[0],fs[1]],km2=[fs[2],fs[3]],rest=fs.slice(4).sort((a,b)=>a.pace-b.pace),cr=[rest[0],rest[1]],me=stats('You'),rival=rest[2];
const course=courseList[Math.floor(hash('course'+wk)*courseList.length)];
const kmP=(a,b)=>clamp(a.km**2/(a.km**2+b.km**2),.12,.88);
const t=(s,c)=>s.pace*c.distanceKm*(1+c.incline*.015);
const crsP=(a,b,c)=>clamp(1/(1+Math.exp((t(a,c)-t(b,c))/(t(b,c)*.04)))+(climber(a.name)-climber(b.name))*.02*(c.incline/5),.1,.9);
return [
{id:'km1-'+wk,kind:'km',a:km1[0],b:km1[1],question:`Who will run more next week: ${km1[0].name} or ${km1[1].name}?`,modelP:kmP(km1[0],km1[1])},
{id:'crs-'+wk,kind:'course',a:cr[0],b:cr[1],course,question:`Who will complete ${course.name} quicker: ${cr[0].name} or ${cr[1].name}?`,modelP:crsP(cr[0],cr[1],course)},
{id:'km2-'+wk,kind:'km',a:km2[0],b:km2[1],question:`Who will run more next week: ${km2[0].name} or ${km2[1].name}?`,modelP:kmP(km2[0],km2[1])},
{id:'you-'+wk,kind:'km',a:me,b:rival,question:`Who will run more next week: You or ${rival.name}?`,modelP:clamp(kmP(me,rival),.08,.88)}]}
const sum=arr=>arr.reduce((n,x)=>n+x.amt,0);
function implied(m){const p=mkt.pools[m.id],seed=12,sa=sum(p.a)+seed*m.modelP,sb=sum(p.b)+seed*(1-m.modelP);return sa/(sa+sb)}
function pushP(m){const h=mkt.hist[m.id];h.push({t:Date.now(),p:implied(m)});if(h.length>360)mkt.hist[m.id]=h.slice(-360)}
function priceAt(m,ts){const h=mkt.hist[m.id];let last=h[0];for(const pt of h){if(pt.t<=ts)last=pt;else break}return last.p}
function ensurePools(m){if(mkt.pools[m.id])return;const pool={a:[],b:[]};mkt.pools[m.id]=pool;mkt.hist[m.id]=[];const others=FRIENDS.filter(f=>f!==m.a.name&&f!==m.b.name),n=6+Math.floor(hash(m.id+'n')*5),now=Date.now(),start=now-3*864e5;mkt.hist[m.id].push({t:start,p:m.modelP});
for(let i=0;i<n;i++){const r=k=>hash(m.id+'bf'+i+k),who=others[Math.floor(r(1)*others.length)],side=r(2)<implied(m)*.7+m.modelP*.3?'a':'b',e={who,amt:5+Math.floor(r(3)*4)*5,t:start+(now-start)*(i+1)/(n+1),p:0};pool[side].push(e);e.p=implied(m);mkt.hist[m.id].push({t:e.t,p:e.p})}saveM()}
function graph(m){const h=mkt.hist[m.id],n=h.length,X=i=>(n<2?300:i/(n-1)*300).toFixed(1),Y=p=>(60-p*52-4).toFixed(1),line=h.map((pt,i)=>`${X(i)},${Y(pt.p)}`).join(' ');return `<svg class="odds-graph" viewBox="0 0 300 60" preserveAspectRatio="none"><line x1="0" y1="${Y(.5)}" x2="300" y2="${Y(.5)}" class="mid"/><polygon points="0,60 ${line} 300,60" class="area"/><polyline points="${line}" class="line"/><circle cx="300" cy="${Y(implied(m))}" r="3" class="dot"/></svg>`}
const TFS=[['6H',216e5],['1D',864e5],['3D',3*864e5],['ALL',Infinity]],tfBy={};
function bigChart(m){const tf=tfBy[m.id]||'ALL',win=TFS.find(x=>x[0]===tf)[1],all=mkt.hist[m.id],cut=Date.now()-win;let h=all.filter(pt=>pt.t>=cut);if(h.length<2)h=all.slice(-2);const n=h.length,X=i=>(i/(n-1)*300).toFixed(1),Y=p=>(150-p*130-10).toFixed(1),line=h.map((pt,i)=>`${X(i)},${Y(pt.p)}`).join(' ');
const hi=Math.max(...h.map(x=>x.p)),lo=Math.min(...h.map(x=>x.p)),pts=JSON.stringify(h.map(pt=>({t:pt.t,p:+pt.p.toFixed(4)})));
return{hi,lo,html:`<div class="chart-wrap" data-pts='${pts}'><div class="chart-tip" hidden></div><svg class="big-chart" viewBox="0 0 300 150" preserveAspectRatio="none">${[.25,.5,.75].map(g=>`<line x1="0" x2="300" y1="${Y(g)}" y2="${Y(g)}" class="grid"/>`).join('')}<polygon points="0,150 ${line} 300,150" class="area"/><polyline points="${line}" class="line"/><line class="hov-line" x1="-9" x2="-9" y1="10" y2="150"/><circle class="hov-dot" cx="-9" cy="-9" r="3.5"/></svg><div class="chart-y"><span>75%</span><span>50%</span><span>25%</span></div><div class="chart-x"><span>${relTime(h[0].t)}</span><span>now</span></div></div>`}}
function analysis(m,p,pot,d24){const fav=p>=.5?m.a:m.b,dog=p>=.5?m.b:m.a,fp=Math.round(Math.max(p,1-p)*100);
const move=Math.abs(d24)<1?'the price has been steady over the last day':`money has moved ${Math.abs(d24).toFixed(1)} pts toward ${d24>=0?m.a.name:m.b.name} in the last 24h`;
if(m.kind==='km')return `${fav.name} is the crowd favourite at ${fp}%${fav.km>=dog.km?` off a bigger week (${fav.km.toFixed(0)} km vs ${dog.km.toFixed(0)} km)`:`, even though ${dog.name} logged more last week (${dog.km.toFixed(0)} km vs ${fav.km.toFixed(0)} km) — the crowd is pricing in a swing`}. ${dog.pace<fav.pace?`${dog.name}'s quicker ${paceStr(dog.pace)}/km pace keeps the market honest`:`${dog.name} needs a bounce-back week to justify the price`}. £${pot.toFixed(0)} staked so far, and ${move}.`;
return `On ${m.course.name} (${m.course.distanceKm} km, incline ${m.course.incline}/10) the model leans ${fav.name} at ${fp}% — ${paceStr(fav.pace)}/km base pace and climbing pedigree LVL ${climber(fav.name)} against ${dog.name}'s LVL ${climber(dog.name)}. ${move[0].toUpperCase()+move.slice(1)}.`}
const rules=m=>m.kind==='km'?`Resolves to whichever runner logs more km in the group run log from Mon 00:00 to Sun 23:59 (verified GPS or logged efforts only). Winning backers split the losing pool pro-rata — no fees. If the winning side has no backers, all stakes are refunded. Demo fast-forward settles early from the model.`:`Resolves to the faster verified effort on ${m.course.name} logged this week. No effort counts as a loss. Winning backers split the losing pool pro-rata — no fees; full refund if the winning side is empty. Demo fast-forward settles early from the model.`;
function detailHTML(m){const p=implied(m),pool=mkt.pools[m.id],pot=sum(pool.a)+sum(pool.b),{hi,lo,html}=bigChart(m),d24=(p-priceAt(m,Date.now()-864e5))*100,tf=tfBy[m.id]||'ALL';
const chips=TFS.map(([k])=>`<button class="tf-chip${k===tf?' active':''}" data-id="${m.id}" data-tf="${k}">${k}</button>`).join('');
const holders=side=>{const agg={};pool[side].forEach(e=>agg[e.who]=(agg[e.who]||0)+e.amt);return Object.entries(agg).sort((x,y)=>y[1]-x[1]).slice(0,3).map(([w,a])=>`${w} £${a.toFixed(0)}`).join(' · ')||'—'};
const acts=[...pool.a.map(e=>({...e,name:m.a.name})),...pool.b.map(e=>({...e,name:m.b.name}))].sort((x,y)=>y.t-x.t).slice(0,6);
return `<div class="market-detail"><div class="tf-row">${chips}<span class="d24 ${d24>=0?'up':'down'}">${d24>=0?'▲':'▼'} ${Math.abs(d24).toFixed(1)} pts / 24h</span></div>${html}<div class="stat-chips"><span>POT £${pot.toFixed(0)}</span><span>LIQUIDITY £${(pot+24).toFixed(0)}</span><span>HIGH ${Math.round(hi*100)}%</span><span>LOW ${Math.round(lo*100)}%</span><span>BETS ${pool.a.length+pool.b.length}</span></div><div class="d-block"><b>MARKET ANALYSIS</b><p>${analysis(m,p,pot,d24)}</p></div><div class="d-block"><b>RESOLUTION RULES</b><p>${rules(m)}</p></div><div class="d-cols"><div class="d-block"><b>TOP HOLDERS</b><div class="d-row"><span>${m.a.name}</span><small>${holders('a')}</small></div><div class="d-row"><span>${m.b.name}</span><small>${holders('b')}</small></div></div><div class="d-block"><b>RECENT ACTIVITY</b>${acts.map(e=>`<div class="d-row"><span>${e.who} £${e.amt} on ${e.name}</span><small>${e.p?Math.round(e.p*100)+'% · ':''}${relTime(e.t)}</small></div>`).join('')}</div></div></div>`}
const myPos=m=>mkt.positions.filter(p=>p.id===m.id);
function projection(m,side,stake){const p=mkt.pools[m.id],win=sum(p[side])+stake,lose=sum(p[side==='a'?'b':'a']);return stake+stake/win*lose}
function posEV(m,pos){const p=implied(m),pool=mkt.pools[m.id],winSum=sum(pool[pos.side])||pos.stake,potential=pos.stake+pos.stake/winSum*sum(pool[pos.side==='a'?'b':'a']);return(pos.side==='a'?p:1-p)*potential}
function bet(m,side,stake){if(m.a.name==='You'||m.b.name==='You')return toast("You can't bet on a market you're racing in");const person=side==='a'?m.a.name:m.b.name;if(mkt.cash<stake)return toast('Not enough balance');mkt.cash-=stake;const e={who:'You',amt:stake,t:Date.now(),p:0};mkt.pools[m.id][side].push(e);e.p=implied(m);mkt.positions.push({id:m.id,q:m.question,side,person,stake,t:e.t});pushP(m);saveM();toast(`£${stake} on ${person} — pot now £${(sum(mkt.pools[m.id].a)+sum(mkt.pools[m.id].b)).toFixed(0)}`);renderMarket()}
function cashOut(pos){const m=markets().find(x=>x.id===pos.id);if(!m||mkt.settled[m.id])return;const ev=posEV(m,pos),pool=mkt.pools[m.id],i=pool[pos.side].findIndex(e=>e.who==='You'&&e.t===pos.t);if(i>=0)pool[pos.side].splice(i,1);mkt.positions=mkt.positions.filter(x=>x!==pos);mkt.cash+=ev;mkt.resolved.unshift({q:m.question,person:pos.person,won:ev>=pos.stake,pnl:ev-pos.stake,cashout:true,date:new Date().toISOString()});pushP(m);saveM();toast(`Cashed out £${ev.toFixed(2)} (staked £${pos.stake})`);renderMarket()}
function settle(m){if(mkt.settled[m.id])return;let aWins;if(m.kind==='km'&&(m.a.name==='You'||m.b.name==='You'))aWins=m.a.km>=m.b.km;else aWins=hash(m.id+weekKey()+'res')<m.modelP;
const winner=aWins?m.a.name:m.b.name,pool=mkt.pools[m.id],winSide=aWins?pool.a:pool.b,loseSide=aWins?pool.b:pool.a,winSum=sum(winSide),loseSum=sum(loseSide),payFor=amt=>winSum>0?amt+amt/winSum*loseSum:amt;
winSide.forEach(e=>{if(e.who!=='You')mkt.banks[e.who]+=payFor(e.amt)-e.amt});
loseSide.forEach(e=>{if(e.who!=='You')mkt.banks[e.who]-=winSum>0?e.amt:0});
let collected=0;mkt.positions=mkt.positions.filter(pos=>{if(pos.id!==m.id)return true;const won=(pos.side==='a')===aWins,payout=won?payFor(pos.stake):(winSum>0?0:pos.stake);collected+=payout;mkt.cash+=payout;mkt.resolved.unshift({q:m.question,person:pos.person,won,pnl:payout-pos.stake,date:new Date().toISOString()});return false});
mkt.settled[m.id]={winner};mkt.hist[m.id].push({t:Date.now(),p:aWins?.97:.03});saveM();toast(`Settled — ${winner} wins the £${(winSum+loseSum).toFixed(0)} pot${collected?` · you collect £${collected.toFixed(2)}`:''}`);renderMarket()}
setInterval(()=>{if(!document.querySelector('#market-mode.active')||!courseList.length)return;const ms=markets();let moved=false;ms.forEach(m=>{if(mkt.settled[m.id])return;ensurePools(m);if(Math.random()<.25){const others=FRIENDS.filter(f=>f!==m.a.name&&f!==m.b.name),who=others[Math.floor(Math.random()*others.length)],side=Math.random()<implied(m)?'a':'b',e={who,amt:5+Math.floor(Math.random()*4)*5,t:Date.now(),p:0};mkt.pools[m.id][side].push(e);e.p=implied(m);pushP(m);toast(`${who} put £${e.amt} on ${side==='a'?m.a.name:m.b.name}`);moved=true}});if(moved){saveM();renderMarket()}},9000);
const openProfiles=new Set(),openDetail=new Set();
const weekKm=()=>{const ws=weekStart();return mkt.efforts.filter(e=>new Date(e.date)>=ws).reduce((n,e)=>n+e.km,0)};
function pledgeHTML(){const wk=weekKey();
if(!mkt.pledge||mkt.pledge.week!==wk){const suggest=Math.max(5,Math.ceil(weekKm())+5);
return `<article class="market-card pledge-card"><div class="market-q"><h3>Back yourself — forfeit pledge</h3><span class="countdown">SELF-STAKE</span></div><p class="muted">You can't bet on your own races — but you can bet on your discipline. Commit money to a weekly km target: hit it and the stake comes home, miss and your friends split it.</p><div class="pledge-form"><label class="pledge-target">TARGET <input id="pledge-km" type="number" min="1" step="1" value="${suggest}"> KM</label><div class="bet-btns">${[10,25,50].map((v,i)=>`<button class="pledge-stake${i===0?' active':''}" data-v="${v}">£${v}</button>`).join('')}</div><button id="pledge-lock" class="lime-button">Lock it in</button></div></article>`}
const p=mkt.pledge,km=weekKm(),met=km>=p.target,pct=Math.min(100,km/p.target*100);
return `<article class="market-card pledge-card"><div class="market-q"><h3>Your pledge: run ${p.target} km this week</h3><span class="${met?'resolved-chip':'countdown'}">£${p.stake} AT STAKE</span></div><div class="pledge-bar"><i style="width:${pct.toFixed(1)}%"></i></div><p class="muted">${km.toFixed(1)} / ${p.target} km · ${met?'target hit — cash it in':'miss and your friends split your stake'}</p><button id="pledge-judge" class="settle-btn">Fast-forward: judge pledge</button></article>`}
function judgePledge(){const p=mkt.pledge;if(!p)return;const met=weekKm()>=p.target;
if(met){mkt.cash+=p.stake;mkt.resolved.unshift({q:`Pledge: ${p.target} km`,person:'You',won:true,pnl:0,pledge:true,date:new Date().toISOString()});toast(`IRONCLAD — pledge met, £${p.stake} comes home`)}
else{FRIENDS.forEach(f=>mkt.banks[f]+=p.stake/FRIENDS.length);mkt.resolved.unshift({q:`Pledge: ${p.target} km`,person:'You',won:false,pnl:-p.stake,pledge:true,date:new Date().toISOString()});toast(`Pledge failed — your friends split £${p.stake}`)}
mkt.pledge=null;saveM();renderMarket()}
function roastLines(){const banks=[['You',mkt.cash],...FRIENDS.map(f=>[f,mkt.banks[f]])],spoon=banks.slice().sort((a,b)=>a[1]-b[1])[0],top=banks.slice().sort((a,b)=>b[1]-a[1])[0],bets=mkt.resolved.filter(r=>!r.pledge),best=bets.slice().sort((a,b)=>b.pnl-a.pnl)[0],worst=bets.slice().sort((a,b)=>a.pnl-b.pnl)[0];
const lines=[`🥄 ${spoon[0]} hold${spoon[0]==='You'?'':'s'} the Wooden Spoon (£${spoon[1].toFixed(0)}) — Sunday's coffees are on ${spoon[0]==='You'?'you':'them'}.`,`💰 ${top[0]} run${top[0]==='You'?'':'s'} the book at £${top[1].toFixed(0)}.`];
if(best&&best.pnl>0)lines.push(`🎯 Sharpest call this week: +£${best.pnl.toFixed(2)} backing ${best.person}.`);
if(worst&&worst.pnl<0)lines.push(`💀 Worst beat: £${(-worst.pnl).toFixed(2)} torched on ${worst.person}.`);
if(mkt.resolved.some(r=>r.pledge&&!r.won))lines.push(`😤 A forfeit pledge got split by the group — discipline is profitable (for everyone else).`);
return lines}
function profileHTML(m,side){const s=side==='a'?m.a:m.b,pct=Math.round((side==='a'?implied(m):1-implied(m))*100),res=resume(s.name),lvl=climber(s.name);
return `<div class="player-profile"><div class="pp-stats"><span>${s.km.toFixed(0)} km/wk</span><span>${paceStr(s.pace)} /km</span><span>${s.runs} runs</span><span>climber LVL ${lvl}</span></div><b>CHALLENGE RÉSUMÉ</b>${res.length?res.map(c=>`<div class="pp-ch">LVL ${c.lvl} · ${c.title} — ${c.where}</div>`).join(''):'<div class="pp-ch muted">No logged challenges yet</div>'}<div class="pp-chance">${pct}% chance in this matchup${m.kind==='course'?` on ${m.course.name} (incline ${m.course.incline}/10, ${m.course.distanceKm} km)`:''}</div></div>`}
function bindCharts(){document.querySelectorAll('.chart-wrap').forEach(w=>{const svg=w.querySelector('svg'),tip=w.querySelector('.chart-tip'),vln=w.querySelector('.hov-line'),dot=w.querySelector('.hov-dot'),pts=JSON.parse(w.dataset.pts),n=pts.length;
w.onmousemove=e=>{const r=svg.getBoundingClientRect(),fx=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),i=Math.round(fx*(n-1)),pt=pts[i],x=(i/(n-1)*300).toFixed(1);vln.setAttribute('x1',x);vln.setAttribute('x2',x);dot.setAttribute('cx',x);dot.setAttribute('cy',(150-pt.p*130-10).toFixed(1));tip.hidden=false;tip.style.left=Math.min(80,fx*100).toFixed(1)+'%';tip.textContent=Math.round(pt.p*100)+'% · '+relTime(pt.t)};
w.onmouseleave=()=>{tip.hidden=true;vln.setAttribute('x1',-9);vln.setAttribute('x2',-9);dot.setAttribute('cx',-9)}})}
function renderMarket(){const list=document.querySelector('#market-list');if(!list||!courseList.length)return;
if(mkt.week!==weekKey()){mkt.positions.forEach(p=>mkt.cash+=p.stake);mkt.positions=[];if(mkt.pledge){mkt.cash+=mkt.pledge.stake;mkt.pledge=null}mkt.pools={};mkt.hist={};mkt.settled={};mkt.week=weekKey();saveM()}
const ms=markets();ms.forEach(ensurePools);document.querySelector('#market-balance').textContent='£'+mkt.cash.toFixed(2);
list.innerHTML=pledgeHTML()+ms.map(m=>{const p=implied(m),st=mkt.settled[m.id],hasYou=m.a.name==='You'||m.b.name==='You',pool=mkt.pools[m.id],pot=sum(pool.a)+sum(pool.b),open=openDetail.has(m.id);
const statLine=m.kind==='km'?`${m.a.name}: ${m.a.km.toFixed(0)} km last wk · ${paceStr(m.a.pace)}/km — ${m.b.name}: ${m.b.km.toFixed(0)} km · ${paceStr(m.b.pace)}/km`:`${m.a.name}: ${paceStr(m.a.pace)}/km, climber LVL ${climber(m.a.name)} — ${m.b.name}: ${paceStr(m.b.pace)}/km, LVL ${climber(m.b.name)}`;
const row=(side,person,prob)=>{const key=m.id+':'+side,backers=pool[side].slice(-3).map(e=>`${e.who} £${e.amt}`).join(' · ');
const btns=st?'':hasYou?(person==='You'?'<span class="self-note">can\'t back yourself</span>':'<span class="self-note">you\'re racing in this market</span>'):[5,10,25].map(v=>`<button class="bet-btn" data-id="${m.id}" data-side="${side}" data-stake="${v}" title="Returns £${projection(m,side,v).toFixed(2)} if right">£${v}</button>`).join('');
return `<div class="outcome-row${st&&st.winner===person?' won':''}"><button class="o-name-btn" data-key="${key}">${person} ▾</button><em>${Math.round(prob*100)}%</em><span class="o-odds">£${sum(pool[side]).toFixed(0)} in</span><div class="bet-btns">${btns}</div></div>${backers?`<div class="backers">${backers}</div>`:''}${openProfiles.has(key)?profileHTML(m,side):''}`};
const pos=myPos(m).map(x=>{const winSum=sum(pool[x.side])||x.stake,ret=x.stake+x.stake/winSum*sum(pool[x.side==='a'?'b':'a']);return `<div class="pos-note">You're in for £${x.stake} on ${x.person} — returns £${ret.toFixed(2)} if right (winners split the losers' pot)</div>`}).join('');
return `<article class="market-card${hasYou?' has-you':''}" data-id="${m.id}"><div class="market-q"><h3>${m.question}</h3>${st?`<span class="resolved-chip">RESOLVED · ${st.winner.toUpperCase()} WON</span>`:'<span class="countdown">CLOSES SUN 23:59</span>'}</div><p class="muted statline">${statLine}</p>${open?detailHTML(m):graph(m)}<button class="detail-btn" data-id="${m.id}">${open?'Hide details ▴':'Details & analysis ▾'}</button>${row('a',m.a.name,p)}${row('b',m.b.name,1-p)}${pos}${st?'':`<button class="settle-btn" data-id="${m.id}">Fast-forward: settle market</button>`}<span class="vol">£${pot.toFixed(0)} POT</span></article>`}).join('');
list.querySelectorAll('.bet-btn').forEach(b=>b.onclick=()=>bet(ms.find(x=>x.id===b.dataset.id),b.dataset.side,Number(b.dataset.stake)));
list.querySelectorAll('.settle-btn').forEach(b=>b.onclick=()=>settle(ms.find(x=>x.id===b.dataset.id)));
list.querySelectorAll('.o-name-btn').forEach(b=>b.onclick=()=>{openProfiles.has(b.dataset.key)?openProfiles.delete(b.dataset.key):openProfiles.add(b.dataset.key);renderMarket()});
list.querySelectorAll('.detail-btn').forEach(b=>b.onclick=()=>{openDetail.has(b.dataset.id)?openDetail.delete(b.dataset.id):openDetail.add(b.dataset.id);renderMarket()});
list.querySelectorAll('.tf-chip').forEach(b=>b.onclick=()=>{tfBy[b.dataset.id]=b.dataset.tf;renderMarket()});
const lock=list.querySelector('#pledge-lock');if(lock){list.querySelectorAll('.pledge-stake').forEach(b=>b.onclick=()=>list.querySelectorAll('.pledge-stake').forEach(x=>x.classList.toggle('active',x===b)));lock.onclick=()=>{const target=Math.max(0,Math.round(Number(list.querySelector('#pledge-km').value)||0)),stake=Number(list.querySelector('.pledge-stake.active').dataset.v);if(!target)return toast('Set a km target');if(mkt.cash<stake)return toast('Not enough balance');mkt.cash-=stake;mkt.pledge={week:weekKey(),target,stake};saveM();toast(`Pledge locked — ${target} km or your friends split £${stake}`);renderMarket()}}
const judge=list.querySelector('#pledge-judge');if(judge)judge.onclick=judgePledge;
bindCharts();
const el=document.querySelector('#market-side'),posEVs=mkt.positions.reduce((n,x)=>{const m=ms.find(mm=>mm.id===x.id);return n+(m&&!mkt.settled[x.id]?posEV(m,x):x.stake)},0),banks=[['You',mkt.cash],...FRIENDS.map(f=>[f,mkt.banks[f]])].sort((a,b)=>b[1]-a[1]);
el.innerHTML=`<div class="wallet-card"><span class="eyebrow">YOUR BALANCE</span><strong>£${mkt.cash.toFixed(2)}</strong><small>PORTFOLIO £${(mkt.cash+posEVs).toFixed(2)} incl. positions · started £100</small><small class="earned-line">EARNED BY RUNNING £${mkt.earned.toFixed(2)} — your legs mint your bankroll</small><div class="wallet-demo"><button id="set-balance">Demo: set balance</button><span id="balance-edit" hidden><input id="balance-input" type="number" min="0" step="0.01" placeholder="£"><button id="balance-apply">Set</button></span></div></div><div class="side-block roast-block"><b>THE ROAST · WEEKLY</b>${roastLines().map(l=>`<p class="roast-line">${l}</p>`).join('')}</div><div class="side-block"><b>OPEN POSITIONS</b>${mkt.positions.length?mkt.positions.map((x,i)=>{const m=ms.find(mm=>mm.id===x.id),ev=m&&!mkt.settled[x.id]?posEV(m,x):x.stake,d=ev-x.stake;return `<div class="side-row"><span>${x.person}<small> £${x.stake} staked · EV <i class="${d>=0?'up':'down'}">${d>=0?'+':''}£${d.toFixed(2)}</i></small></span><button class="cashout-btn" data-i="${i}">Cash out £${ev.toFixed(2)}</button></div>`}).join(''):'<p class="muted">No bets yet — back a friend.</p>'}</div><div class="side-block"><b>SETTLED</b>${mkt.resolved.length?mkt.resolved.slice(0,6).map(r=>`<div class="side-row"><span>${r.person}<small> ${r.cashout?'cash-out':r.won?'won':'lost'}</small></span><strong class="${r.pnl>=0?'up':'down'}">${r.pnl>=0?'+':''}£${r.pnl.toFixed(2)}</strong></div>`).join(''):'<p class="muted">Nothing settled yet.</p>'}</div><div class="side-block"><b>TOP PREDICTORS</b>${banks.map((r,i)=>`<div class="side-row${r[0]==='You'?' mine':''}"><span>${['🥇','🥈','🥉'][i]||'·'} ${r[0]}${i===banks.length-1?' 🥄':''}</span><strong>£${r[1].toFixed(2)}</strong></div>`).join('')}</div>`;
el.querySelectorAll('.cashout-btn').forEach(b=>b.onclick=()=>cashOut(mkt.positions[Number(b.dataset.i)]));
el.querySelector('#set-balance').onclick=()=>{const ed=el.querySelector('#balance-edit'),inp=el.querySelector('#balance-input');ed.hidden=false;inp.value=mkt.cash.toFixed(2);inp.focus();inp.select()};
const applyBal=()=>{const v=Number(el.querySelector('#balance-input').value);if(!isFinite(v)||v<0)return toast('Enter a valid amount');mkt.cash=Math.round(v*100)/100;saveM();toast('Balance set to £'+mkt.cash.toFixed(2));renderMarket()};
el.querySelector('#balance-apply').onclick=applyBal;el.querySelector('#balance-input').onkeydown=e=>{if(e.key==='Enter')applyBal()}}
window.__renderMarket=renderMarket;
